/**
 * DSO (Deep Sky Object) Service
 *
 * Provides verified astronomical object data from the embedded Messier / NGC
 * catalogue.  All data originates from the Messier Catalogue and NASA/IPAC
 * Extragalactic Database – nothing is generated by the AI at query time, so
 * the user can trust every figure that is attributed to this service.
 */

const path = require('path');
const catalog = require('../data/dso-catalog.json');

class DSOService {
  constructor() {
    // Build a lookup index at startup so every query is O(1)
    this.index = new Map();

    for (const obj of catalog) {
      // Primary key: "M31", "M42", etc.
      this.index.set(obj.id.toLowerCase(), obj);

      // NGC / IC id: "ngc 224", "ic 4725"
      if (obj.ngc_id) {
        this.index.set(obj.ngc_id.toLowerCase(), obj);
        // Also without the space: "ngc224"
        this.index.set(obj.ngc_id.toLowerCase().replace(/\s+/g, ''), obj);
      }

      // Common name: "andromeda galaxy"
      if (obj.common_name) {
        this.index.set(obj.common_name.toLowerCase(), obj);
      }

      // Aliases: "andromeda", "great andromeda nebula"
      for (const alias of obj.aliases || []) {
        this.index.set(alias.toLowerCase(), obj);
      }
    }

    console.log(`DSO catalog loaded: ${catalog.length} objects indexed`);
  }

  /**
   * Find an object by any recognisable name or designation.
   *
   * @param {string} query  e.g. "M31", "Andromeda", "NGC 224", "Orion Nebula"
   * @returns {object|null} The catalog entry, or null if not found.
   */
  findObject(query) {
    if (!query || typeof query !== 'string') return null;

    const normalised = query.trim().toLowerCase();

    // Direct lookup
    if (this.index.has(normalised)) {
      return this.index.get(normalised);
    }

    // Try adding a space: "m31" → "m 31"
    const withSpace = normalised.replace(/^(m|ngc|ic)(\d+)$/i, '$1 $2');
    if (this.index.has(withSpace)) {
      return this.index.get(withSpace);
    }

    // Try removing a space: "m 31" → "m31"
    const noSpace = normalised.replace(/\s+/g, '');
    if (this.index.has(noSpace)) {
      return this.index.get(noSpace);
    }

    // Partial match on common_name and aliases (last resort)
    for (const obj of catalog) {
      if (obj.common_name && obj.common_name.toLowerCase().includes(normalised)) {
        return obj;
      }
      for (const alias of obj.aliases || []) {
        if (alias.toLowerCase().includes(normalised)) {
          return obj;
        }
      }
    }

    return null;
  }

  /**
   * Return objects that are well-placed for the given month.
   *
   * @param {number}   month      1–12
   * @param {string}   [type]     Optional filter: 'galaxy', 'globular_cluster', etc.
   * @param {string}   [maxDiff]  Max imaging difficulty: 'easy', 'moderate', 'challenging'
   * @returns {object[]}
   */
  getObjectsForMonth(month, type = null, maxDiff = null) {
    const difficultyRank = { easy: 1, moderate: 2, intermediate: 2, challenging: 3, very_challenging: 4 };
    const maxRank = maxDiff ? (difficultyRank[maxDiff] || 99) : 99;

    return catalog.filter(obj => {
      if (!obj.best_months || !obj.best_months.includes(month)) return false;
      if (type && obj.type !== type) return false;
      const rank = difficultyRank[obj.imaging_difficulty] || 99;
      if (rank > maxRank) return false;
      return true;
    });
  }

  /**
   * Calculate whether an object fits in a field of view.
   *
   * @param {object} obj              Catalog entry (from findObject)
   * @param {number} fovMajorDeg      FOV major axis in degrees
   * @param {number} fovMinorDeg      FOV minor axis in degrees
   * @returns {{ fits: boolean, panelsNeeded: number, note: string }}
   */
  checkFOVFit(obj, fovMajorDeg, fovMinorDeg) {
    if (!obj.angular_size_major) {
      return { fits: true, panelsNeeded: 1, note: 'Object size unknown – assume fits' };
    }

    const objMajorDeg = obj.angular_size_major / 60;
    const objMinorDeg = (obj.angular_size_minor || obj.angular_size_major) / 60;

    const fitsInOneDimension =
      objMajorDeg <= fovMajorDeg * 0.8 && objMinorDeg <= fovMinorDeg * 0.8;

    if (fitsInOneDimension) {
      return {
        fits: true,
        panelsNeeded: 1,
        note: `Object (${obj.angular_size_major}′×${obj.angular_size_minor || obj.angular_size_major}′) fits with room to spare in your ${(fovMajorDeg * 60).toFixed(0)}′×${(fovMinorDeg * 60).toFixed(0)}′ field of view.`,
      };
    }

    // How many panels are needed?
    const panelsH = Math.ceil(objMajorDeg / (fovMajorDeg * 0.7));
    const panelsV = Math.ceil(objMinorDeg / (fovMinorDeg * 0.7));
    const panelsNeeded = panelsH * panelsV;

    return {
      fits: false,
      panelsNeeded,
      note: `Object (${obj.angular_size_major}′×${obj.angular_size_minor || obj.angular_size_major}′) is larger than your ${(fovMajorDeg * 60).toFixed(0)}′×${(fovMinorDeg * 60).toFixed(0)}′ field of view. A ${panelsH}×${panelsV} mosaic (${panelsNeeded} panel${panelsNeeded > 1 ? 's' : ''}) would capture the full object.`,
    };
  }

  /**
   * Calculate field of view from telescope + camera specs.
   *
   * @param {number} focalLengthMm    Telescope focal length in mm
   * @param {number} sensorWidthMm    Camera sensor width in mm
   * @param {number} sensorHeightMm   Camera sensor height in mm
   * @returns {{ fovWidthDeg: number, fovHeightDeg: number, fovWidthArcmin: number, fovHeightArcmin: number }}
   */
  calculateFOV(focalLengthMm, sensorWidthMm, sensorHeightMm) {
    const RAD_TO_DEG = 180 / Math.PI;
    const fovWidthDeg  = 2 * Math.atan(sensorWidthMm  / (2 * focalLengthMm)) * RAD_TO_DEG;
    const fovHeightDeg = 2 * Math.atan(sensorHeightMm / (2 * focalLengthMm)) * RAD_TO_DEG;
    return {
      fovWidthDeg:     Math.round(fovWidthDeg  * 100) / 100,
      fovHeightDeg:    Math.round(fovHeightDeg * 100) / 100,
      fovWidthArcmin:  Math.round(fovWidthDeg  * 60  * 10) / 10,
      fovHeightArcmin: Math.round(fovHeightDeg * 60  * 10) / 10,
    };
  }

  /** Return the full catalog array. */
  getAll() {
    return catalog;
  }
}

module.exports = new DSOService();
